---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: surferslookout-db
  namespace: alpha
  description: Stores data for the surfers lookout service
spec:
  type: database
  location: surfers-org
  owner: group:surfers-crew
  system: surfers-system

