apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: surfers-org
spec:
  type: url
  targets:
    - https://github.com/davlloyd/surfers-gitops/blob/main/catalog/catalog-users.yaml
    - https://github.com/davlloyd/surfers-gitops/blob/main/catalog/catalog-system.yaml
    - https://github.com/davlloyd/surfers-gitops/blob/main/catalog/catalog-resources.yaml
    - https://github.com/davlloyd/surfers-gitops/blob/main/workloads/surfers-api/catalog-info.yaml
    - https://github.com/davlloyd/surfers-gitops/blob/main/workloads/surfers-web/catalog-info.yaml
