
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: surfers-crew
  namespace: default
  description: Team focused on the Surfer system
spec:
  type: team
  profile:
    displayName: Surfer Crew
  parent: surfers-org
  children: []

---

apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: surfer-a
  namespace: default
spec:
  profile:
    displayName: Surfer Dude A
  memberOf: [surfers-crew]

---
