 
---
apiVersion: v1
kind: Service
metadata:
  name: telegraf-service
spec:
  type: LoadBalancer
  ports:
  - port: 3306
  selector:
    app: telegraf-agent

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: telegraf-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1

kind: ConfigMap
metadata:
  name: telegraf-config
data:
  influxdb.conf: |+
    reporting-disabled = false
    bind-address = "127.0.0.1:8088"

    [meta]
      dir = "/var/lib/influxdb/meta"
      retention-autocreate = true
      logging-enabled = true    

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-agent
  labels:
    app: telegraf-agent
spec:
  selector:
    matchLabels:
      app: telegraf-agent
  template:
    metadata:
      labels:
        app: telegraf-agent
    spec:
      containers:
      - image: wavefronthq/telegraf:latest
        name: agent
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: telegraf-data
          mountPath: /etc/telegraf/telegraf.d
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: surferslookout-db-data
