#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: team-access
type: kubernetes.io/basic-auth
stringData:
  username: #@ data.values.imported.team-secret-store[ns.name].username
  password: #@ data.values.imported.team-secret-store[ns.name].password
  