apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  name: surfers-api
  namespace: accelerator-system
spec:
  git:
    url: https://github.com/davlloyd/surfers-api
    ref:
      branch: main
